dprescriptivemaintenance40/Predictive-Maintenance

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Models/Prescriptive/CentrifugalPumpModel/CentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/dashboard/dashboard.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-configuration/prescriptive-configuration.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
> Amin development

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Models/RecycleBinModel/RecycleBinCentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-bin.component.ts
Recycle bin Completely working fine
> Recycle bin bug fix

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/Token.Interceptor.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/dashboard/dashboard.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/dashboard/dashboard.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/dashboard/dashboard.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/education/education.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.routing.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/report/report.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/login-registration/login-registration.component.ts
Done with design and dashboard changes
> Removed dashboard for now instead of that showing DPM Education

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.spec.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/prescriptive.module.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/prescriptive.routing.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-bin.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-model.ts
fmea list done and prescriptive update consequence added, some bug fix in update
> Amin fmea list

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.ts
> Externally FCA Added

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/Token.Interceptor.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/css/bootstrap.css
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/css/print.css
> Report print

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
> Shivani fca

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-display/prescriptive-display.component.ts
Prescriptive Display Bug has been fixed and working Properly
> Prescriptive Display Working Properly

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
> Shivani design changes

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.ts
> Report Bug Fix

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
> MSS Dynamic Demo Added

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
Fca select box is missing that also added and prescriptive authentication is also addded
> Amin only prescriptive login

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Models/Prescriptive/CentrifugalPumpModel/CentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.html
1) FMEA Configuration Option removed From UserType = 4
2) Webal Completed Successfully
3) FCA all completed
4) Prescriptive Report Select option enables disabled as per FMEA FCA MSS added in Tree
> Amin webal algorithm

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
FCA has modified according to need of webal yes and no
> FCA modified

- DPMMVCCore/DPM_Testing/Controllers/Compressors/ScrewCompressor/ScrewCompressorFuturePredictionAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Compressors/ScrewCompressor/ScrewCompressorPredictionChartAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Compressors/ScrewCompressor/ScrewCompressorTrainChartAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Compressors/ScrewCompressor/ScrewCompressureAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Pumps/CentrifugalPump/CenterifugalPumpAPIController.cs
async and await has been added to all api's
> Async Await is added to all api's

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Models/Prescriptive/CentrifugalPumpModel/CentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
Update FCA and MSS Completed Successfully
> Amin 27 april update fca&mss

- DPMMVCCore/DPM_Testing/Models/RecycleBinModel/RecycleBinCentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-bin.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-model.ts
Recycle Bin Completed and MSS template Hide bug Fixed
> Amin 30 april recyclebin

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/app.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/app.module.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-configuration/prescriptive-configuration.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/Shared/prescritpive.bl.service.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/Shared/prescritpive.dl.service.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/shared/config.service.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/Config/appsettings.json
> BLDL added

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/prediction/prediction.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/train/train.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/Config/appsettings.json
> updated prediction and ruleengine url

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-list/prescriptive-list.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/MSS_Library/mss_library.json
> Task 3 and 4th complete

- DPMMVCCore/DPM_Testing/Controllers/Compressors/ScrewCompressor/ScrewCompressureAPIController.cs
- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/Models/Prescriptive/CentrifugalPumpModel/CentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-display/prescriptive-display.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/recycle-bin/recycle-bin.component.ts
checked and bugs has been removed
> Shivani new fca&mss changes

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
> changed MSS Formula

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
> MTBF in Update Complete

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
> Shivani new design changes

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/prediction/prediction.component.ts
1) Single prediction Bug fixed
2) Bulk prediction working fine
> Prediction bug fix

- DPMMVCCore/DPM_Testing/Controllers/Pumps/CentrifugalPump/CenterifugalPumpAPIController.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump.API.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump.component.ts
> Pump data upload

- DPMMVCCore/DPM_Testing/Models/Prescriptive/CentrifugalPumpModel/CentrifugalPumpPrescriptiveModel.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
> MSS Enhancement Completed

- DPMMVCCore/DPM_Testing/Controllers/Prescriptive/PrescriptiveAPIController.cs
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.html
> MSS Changes Done

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-report/prescriptive-report.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
> Changes are done

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
> Changes done

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/MSS_Library/mss_library.json
> Add Back button

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/MSS_Library/mss_library.json
> Shivani prescriptive update 27/5/21

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/RCA/rca.component.ts
> Amin rca bug fix

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/compressor.module.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-predictiondata-upload/screw-compressor-predictiondata-upload.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-predictiondata-upload/screw-compressor-predictiondata-upload.component.spec.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-predictiondata-upload/screw-compressor-predictiondata-upload.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-traindata-upload/screw-compressor-traindata-upload.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-traindata-upload/screw-compressor-traindata-upload.component.spec.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Compressor/ScrewCompressor/screw-compressor-traindata-upload/screw-compressor-traindata-upload.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump-predictiondata-upload/centrifugal-pump-predictiondata-upload.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump-predictiondata-upload/centrifugal-pump-predictiondata-upload.component.spec.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump-predictiondata-upload/centrifugal-pump-predictiondata-upload.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump-traindata-upload/centrifugal-pump-traindata-upload.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/Pump/centrifugal-pump/centrifugal-pump-traindata-upload/centrifugal-pump-traindata-upload.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.module.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/home.routing.ts
> Upload Data

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.scss
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-consequences/prescriptive-consequences.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-update/prescriptive-update.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/MSS/mss-add/mss-add.component.ts
> All changes done

- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FCA/fca-add/fca-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/FMEA/prescriptive-add/prescriptive-add.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/RCA/rca.component.html
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/app/home/prescriptive/RCA/rca.component.ts
- DPMMVCCore/DPM_Testing/wwwroot/DPM/src/assets/Library/mss_library.json
> 2 aug rca fix
